[package]
name = "lares"
version = "0.1.0"
authors = ["Zeyi Fan <fanzeyi1994@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.23"
anyhow = "1.0.32"
tide = "0.13.0"
async-std = { version = "1.6", features = ["attributes"] }
r2d2_sqlite = "0.16.0"
r2d2 = "0.8.9"
